directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(4,0,3,0,4)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(4,0,3,0,4)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(16,0,8,0,16)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#13 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(16,0,8,0,16)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#51 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_x#1:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,7,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#1:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#7:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#2:if:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#8:if:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#1:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#7:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#2:else:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#8:else:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#11:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#3
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#6:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#3
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#5:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#4
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#6:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#4
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#5:else:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#5
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#11:if:acc#2 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,9,0,10)#5
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#6:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#1:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#7:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#5:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#11:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#8:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/moy#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,8,0,9)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#6:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#48 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#5:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#11:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#1
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#2:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#8:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#1:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/sub#7:if:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(10,0,9,0,11)#2
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,6,0,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#49 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,6,0,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_x:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_x#2:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_x:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#42 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,2,1,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,6,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y#2:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,6,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#44 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y#1:acc#8 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y#2:acc#7 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(8,0,3,0,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#49 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_y#2:acc#5 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,2,1,9)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_x:acc#1 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_x#1:acc#3 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#38 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,1,7)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y:acc#45 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,0,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#44 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(7,0,2,0,8)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_x:acc#4 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/passe_y#1:acc#47 RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(9,0,8,0,10)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_x:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(5,0,5,0,5)
directive set /Main_Trans_Ond_Opt/Main_Trans_Ond_Opt:core/WAIT_DP#1/copy_x#2:acc RESOURCE_NAME mgc_Xilinx-ARTIX-7-1_beh_psr.mgc_add(5,0,5,0,5)
